### ISSUE TITLE
Product Description and Images 

### ISSUE THREAD

**Issue by saurabhbahadur** [Anna-012/Ecommerce-app#1]
z - index property 

```css
.pro img{
    position: relative;
    z-index: -10;
    
  }
  .des {
    position: relative;
    z-index: -10;
    
  }
```
